drop table if exists accounts;
drop table if exists cars;
drop table if exists fuel_types;
drop table if exists orders;
drop table if exists return_requests;
drop table if exists transmissions;
create table accounts (role varchar(31) not null, id integer not null auto_increment, email varchar(255), full_name varchar(255), login varchar(255), password varchar(255), birthday_year integer, primary key (id)) type=MyISAM;
create table cars (id integer not null auto_increment, available bit not null, fuel_type_id integer, mileage integer not null, model varchar(255), number varchar(255), price_hour double precision, transmission_id integer, year_of_issue integer, primary key (id)) type=MyISAM;
create table fuel_types (id integer not null auto_increment, name varchar(255), primary key (id)) type=MyISAM;
create table orders (id integer not null auto_increment, car_id integer, client_id integer, closed bit not null, order_date datetime, passport_data varchar(255), period integer not null, price double precision not null, return_date datetime, primary key (id)) type=MyISAM;
create table return_requests (id integer not null auto_increment, description varchar(255), order_id integer, repair_cost double precision, return_date datetime, return_mark bit, primary key (id)) type=MyISAM;
create table transmissions (id integer not null auto_increment, name varchar(255), primary key (id)) type=MyISAM;
alter table accounts add constraint UK_n7ihswpy07ci568w34q0oi8he unique (email);
alter table accounts add constraint UK_cc2c9baeppipgy2rjeccwcqs0 unique (login);
alter table return_requests add constraint UK_mlyu5yxuty6xy4bndr5rrnfr0 unique (order_id);
alter table cars add constraint FK4pcp6qj7ex88765evtdq3oyt9 foreign key (fuel_type_id) references fuel_types (id);
alter table cars add constraint FKc61a4jv9119g5jbpi51wsu876 foreign key (transmission_id) references transmissions (id);
alter table orders add constraint FKd2p23ixwrrt395glgi9nnbj23 foreign key (car_id) references cars (id);
alter table orders add constraint FK5d2pybraac6nktifbh8hsmraw foreign key (client_id) references accounts (id);
alter table return_requests add constraint FKbski88d6kewx0cbj5pk7nes01 foreign key (order_id) references orders (id);
drop table if exists accounts;
drop table if exists cars;
drop table if exists fuel_types;
drop table if exists orders;
drop table if exists return_requests;
drop table if exists transmissions;
create table accounts (role varchar(31) not null, id integer not null auto_increment, email varchar(255), full_name varchar(255), login varchar(255), password varchar(255), birthday_year integer, primary key (id)) type=MyISAM;
create table cars (id integer not null auto_increment, available bit not null, fuel_type_id integer, mileage integer not null, model varchar(255), number varchar(255), price_hour double precision, transmission_id integer, year_of_issue integer, primary key (id)) type=MyISAM;
create table fuel_types (id integer not null auto_increment, name varchar(255), primary key (id)) type=MyISAM;
create table orders (id integer not null auto_increment, car_id integer, client_id integer, closed bit not null, order_date datetime, passport_data varchar(255), period integer not null, price double precision not null, return_date datetime, primary key (id)) type=MyISAM;
create table return_requests (id integer not null auto_increment, description varchar(255), order_id integer, repair_cost double precision, return_date datetime, return_mark bit, primary key (id)) type=MyISAM;
create table transmissions (id integer not null auto_increment, name varchar(255), primary key (id)) type=MyISAM;
alter table accounts add constraint UK_n7ihswpy07ci568w34q0oi8he unique (email);
alter table accounts add constraint UK_cc2c9baeppipgy2rjeccwcqs0 unique (login);
alter table return_requests add constraint UK_mlyu5yxuty6xy4bndr5rrnfr0 unique (order_id);
alter table cars add constraint FK4pcp6qj7ex88765evtdq3oyt9 foreign key (fuel_type_id) references fuel_types (id);
alter table cars add constraint FKc61a4jv9119g5jbpi51wsu876 foreign key (transmission_id) references transmissions (id);
alter table orders add constraint FKd2p23ixwrrt395glgi9nnbj23 foreign key (car_id) references cars (id);
alter table orders add constraint FK5d2pybraac6nktifbh8hsmraw foreign key (client_id) references accounts (id);
alter table return_requests add constraint FKbski88d6kewx0cbj5pk7nes01 foreign key (order_id) references orders (id);
